export const images = {
  BOTTOM_TAB_1: require('../../assets/bottom_tab_1.png'),
  BOTTOM_TAB_2: require('../../assets/bottom_tab_2.png'),
  BOTTOM_TAB_3: require('../../assets/bottom_tab_3.png'),
  BOTTOM_TAB_5: require('../../assets/bottom_tab_5.png'),
  header_menu_left_arrow: require('../../assets/header_menu_left_arrow.png'),
  header_menu_launcher: require('../../assets/header_menu_launcher.png'),
  header_menu_drawer: require('../../assets/header_menu_drawer.png'),
  header_menu_refresh: require('../../assets/header_menu_refresh.png'),
  header_menu_message: require('../../assets/header_menu_message.png'),
  header_menu_horse: require('../../assets/header_menu_horse.png'),
  header_menu_ewallet: require('../../assets/header_menu_ewallet.png'),
  header_menu_account: require('../../assets/header_menu_account.png'),
  racing_touch_icon: require('../../assets/raceingtouch_icon.png'),
  livePlay: require('../../assets/live_play.png'),
  allUpMoreArrowLightIcon: require('../../assets/ic_all_up_more_arrow_light.png'),
  raceCardUnlikeLight: require('../../assets/raceCard_unlike_light.png'),
  silkScrDark: require('../../assets/silk_scr_dark.png'),
};
